definitions:
  domain.CreateDriverRequest:
    properties:
      id:
        type: string
      location:
        $ref: '#/definitions/domain.Point'
    required:
    - location
    type: object
  domain.Driver:
    properties:
      created_at:
        type: string
      id:
        type: string
      location:
        $ref: '#/definitions/domain.Point'
      updated_at:
        type: string
    required:
    - location
    type: object
  domain.Point:
    properties:
      coordinates:
        items:
          type: number
        type: array
      type:
        type: string
    required:
    - coordinates
    - type
    type: object
  domain.SearchRequest:
    properties:
      limit:
        minimum: 0
        type: integer
      location:
        $ref: '#/definitions/domain.Point'
      radius:
        description: radius in meters
        type: number
    required:
    - location
    - radius
    type: object
  http.APIResponse:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
  description: A service for finding nearby drivers
  title: Driver Location Service API
  version: "1.0"
paths:
  /api/v1/drivers:
    post:
      consumes:
      - application/json
      description: Create one or multiple drivers in a single request. Supports both
        single driver and batch operations.
      parameters:
      - description: Driver(s) info - send array with single element for one driver,
          multiple elements for batch
        in: body
        name: drivers
        required: true
        schema:
          items:
            $ref: '#/definitions/domain.CreateDriverRequest'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.APIResponse'
      security:
      - X-API-KEY: []
      summary: Create driver(s)
      tags:
      - drivers
  /api/v1/drivers/{id}:
    delete:
      description: Delete a driver by its ID
      parameters:
      - description: Driver ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.APIResponse'
      security:
      - X-API-KEY: []
      summary: Delete driver by ID
      tags:
      - drivers
    get:
      description: Get a driver by its ID
      parameters:
      - description: Driver ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.APIResponse'
      security:
      - X-API-KEY: []
      summary: Get driver by ID
      tags:
      - drivers
    put:
      consumes:
      - application/json
      description: Update a driver's information by ID
      parameters:
      - description: Driver ID
        in: path
        name: id
        required: true
        type: string
      - description: Driver info
        in: body
        name: driver
        required: true
        schema:
          $ref: '#/definitions/domain.Driver'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.APIResponse'
      security:
      - X-API-KEY: []
      summary: Update driver by ID
      tags:
      - drivers
  /api/v1/drivers/{id}/location:
    patch:
      consumes:
      - application/json
      description: Update a driver's location by ID
      parameters:
      - description: Driver ID
        in: path
        name: id
        required: true
        type: string
      - description: New location
        in: body
        name: location
        required: true
        schema:
          $ref: '#/definitions/domain.Point'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.APIResponse'
      security:
      - X-API-KEY: []
      summary: Update driver location
      tags:
      - drivers
  /api/v1/drivers/search:
    post:
      consumes:
      - application/json
      description: Find drivers near a given location
      parameters:
      - description: Search params
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/domain.SearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.APIResponse'
      security:
      - X-API-KEY: []
      summary: Search nearby drivers
      tags:
      - drivers
  /health:
    get:
      consumes:
      - application/json
      description: Check if the service is healthy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.APIResponse'
      summary: Health check endpoint
      tags:
      - health
securityDefinitions:
  X-API-KEY:
    description: Type X-API-KEY followed by a space and API key.
    in: header
    name: X-API-KEY
    type: apiKey
swagger: "2.0"
